spring:

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/prography
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB

faker:
  scheme: https
  host: fakerapi.it
  path: /api/v1/users
  locale: ko_KR

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      access: none


